# Generated by Django 3.1.4 on 2020-12-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_imagesrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.imagesrc'),
        ),
        migrations.DeleteModel(
            name='ImageSource',
        ),
    ]
